name: 'Codebase Summary Bot'
description: 'LLM-optimized codebase summarizer for AI code review pipelines, agents, and onboarding.'
author: 'Libin V Babu <www.libin.in>'
branding:
  icon: 'code'
  color: 'blue'

inputs:
  output:
    description: 'Output file path for the codebase summary JSON'
    required: false
    default: 'codebase-summary.json'
  limit:
    description: 'Max items per category (default: 100)'
    required: false
    default: '100'

runs:
  using: 'node20'
  main: 'index.js'
